const videos = [
  "https://jaikvik.in/lab/new-post-video/videos/1.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/2.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/3.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/4.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/5.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/6.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/7.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/8.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/9.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/10.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/11.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/12.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/13.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/14.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/15.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/16.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/17.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/18.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/19.mp4",
  "https://jaikvik.in/lab/new-post-video/thumbnail/video/20.mp4",
  "https://jaikvik.in/lab/new-post-video/videos/GSB-Video.mp4",
];

export default videos;